baseurl = "https://www.rozhkov.me/"
languageCode = "en"
title = "Vladimir Rozhkov"
theme = "humin"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/xrozhokx\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> â™¥"
disqusShortname = "rozhkov"
googleAnalytics = "UA-86260054-1"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Blog about stuff"
keywords = ["tech", "software", "development"]
author = "Vladimir Rozhkov"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/rozhok"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/xpunkerx"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/xrozhokx"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/rozhok"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/rozhok"
fa_icon = "fa-linkedin-square"